{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-defender-to-console-port
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels: 
      {{- include "twistlock-console.selector" . | nindent 6 }}
  action: ALLOW
  rules:
  - to:
    - operation:
        ports: 
        - "{{ .Values.console.ports.communication }}"
{{- end }}
