
{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-sidecar-scraping
  namespace: {{ .Release.Namespace }}
spec:
  selector: {}
  actio: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["monitoring"]  
    to:
    - operation:
        ports: ["15020"]
{{- end}}