apiVersion: v2
name: twistlock
version: 0.11.4-bb.1
appVersion: 22.06.197
dependencies:
  - name: gluon
    version: 0.3.1
    repository: oci://registry.dso.mil/platform-one/big-bang/apps/library-charts/gluon
annotations:
  bigbang.dev/applicationVersions: |
    - Twistlock: 22.06.197
  helm.sh/images: |
    - name: base
      image: registry1.dso.mil/ironbank/big-bang/base:2.0.0
      condition: init.enabled
    - name: console
      image: registry1.dso.mil/ironbank/twistlock/console/console:22.06.197
    - name: defender
      image: registry1.dso.mil/ironbank/twistlock/defender/defender:22.06.197
      condition: defender.enabled
