apiVersion: v2
name: twistlock
version: 0.9.0-bb.1
appVersion: 22.06.179
dependencies:
  - name: gluon
    version: 0.2.10
    repository: oci://registry.dso.mil/platform-one/big-bang/apps/library-charts/gluon
annotations:
  bigbang.dev/applicationVersions: |
    - Twistlock: 22.06.179
