apiVersion: v2
name: twistlock
version: 0.3.0-bb.0
appVersion: 21.08.520
dependencies:
  - name: gluon
    version: 0.1.1
    repository: oci://registry.dso.mil/platform-one/big-bang/apps/library-charts/gluon
annotations:
  bigbang.dev/applicationVersions: |
    - Twistlock: 21.08.520
