apiVersion: v2
name: twistlock
version: 0.0.6-bb.0
appVersion: 21.04.412
dependencies:
  - name: gluon
    version: 0.1.1
    repository: oci://registry.dso.mil/platform-one/big-bang/apps/library-charts/gluon
