apiVersion: v2
name: twistlock
version: 0.14.0-bb.1
appVersion: 31.03.103
dependencies:
  - name: gluon
    version: 0.4.8
    repository: oci://registry1.dso.mil/bigbang
annotations:
  bigbang.dev/applicationVersions: |
    - Twistlock: 31.03.103
  # The base image is utilized when init job is enabled and during upgrades when volumeUpgrade for the console is enabled.
  helm.sh/images: |
    - name: base
      image: registry1.dso.mil/ironbank/big-bang/base:2.1.0
    - name: console
      image: registry1.dso.mil/ironbank/twistlock/console/console:31.03.103
    - name: defender
      image: registry1.dso.mil/ironbank/twistlock/defender/defender:31.03.103
      condition: defender.enabled
