apiVersion: v2
name: twistlock
version: 0.10.0-bb.2
appVersion: 22.06.197
dependencies:
  - name: gluon
    version: 0.3.1
    repository: oci://registry.dso.mil/platform-one/big-bang/apps/library-charts/gluon
annotations:
  bigbang.dev/applicationVersions: |
    - Twistlock: 22.06.197
