apiVersion: v2
name: twistlock
version: 0.8.0-bb.0
appVersion: 22.01.880
dependencies:
  - name: gluon
    version: 0.2.8
    repository: oci://registry.dso.mil/platform-one/big-bang/apps/library-charts/gluon
annotations:
  bigbang.dev/applicationVersions: |
    - Twistlock: 22.01.880
