apiVersion: v2
name: twistlock
version: 0.0.7-bb.1
appVersion: 21.04.439
dependencies:
  - name: gluon
    version: 0.1.1
    repository: oci://registry.dso.mil/platform-one/big-bang/apps/library-charts/gluon
