{{- if and .Values.networkPolicies.enabled .Values.istio.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: istio-controlplane
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            app.kubernetes.io/name: istio-controlplane
{{- end }}
