{{- if and (hasKey $.Values "istio") (hasKey $.Values.istio "hardened") (hasKey $.Values.istio.hardened "tempo") (hasKey $.Values.istio.hardened.tempo "enabled") $.Values.istio.hardened.tempo.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: tempo-authz-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "twistlock-console.selector" . | nindent 6 }}
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: {{ .Values.istio.hardened.tempo.namespaces }}
        principals: {{ .Values.istio.hardened.tempo.principals }}
{{- end }}
