apiVersion: apps/v1
kind: Deployment
metadata:
  name: twistlock-console
  namespace: {{ .Release.Namespace }}
  labels:
    name: twistlock-console
spec:
  replicas: 1
  selector:
    matchLabels:
      name: twistlock-console
  strategy:
    type: Recreate
  template:
    metadata:
      name: twistlock-console
      namespace: {{ .Release.Namespace }}
      labels:
        name: twistlock-console
    spec:
      restartPolicy: Always
      serviceAccountName: twistlock-console
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      containers:
      - name: twistlock-console
        image: {{ .Values.console.image.repository }}:{{ .Values.console.image.tag }}
        ports:
        - name: mgmt-https
          containerPort: 8083
        - name: communication
          containerPort: 8084
        - name: mgmt-http
          containerPort: 8081
        env:
        - name: HIGH_AVAILABILITY_ENABLED
          value: "false"
        - name: CONFIG_PATH
          value: /data/config/twistlock.cfg
        - name: LOG_PROD
          value: "true"
        - name: DATA_RECOVERY_ENABLED
          value: "true"
        - name: COMMUNICATION_PORT
          value: "8084"
        - name: MANAGEMENT_PORT_HTTPS
          value: "8083"
        - name: MANAGEMENT_PORT_HTTP
          value: "8081"
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: twistlock-config-volume
          mountPath: "/data/config/"
        - name: console-persistent-volume
          mountPath: "/var/lib/twistlock"
          subPath: "var/lib/twistlock"
        - name: console-persistent-volume
          mountPath: "/var/lib/twistlock-backup"
          subPath: "var/lib/twistlock-backup"
        - name: syslog-socket
          mountPath: "/dev/log"
      volumes:
      - name: console-persistent-volume
        persistentVolumeClaim:
          claimName: "twistlock-console"
      - name: twistlock-config-volume
        configMap:
          name: twistlock-console
      - name: syslog-socket
        hostPath:
          path: "/dev/log"
