{{- if and .Values.monitoring.enabled .Values.init.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "twistlock-console.name" . }}-metrics-auth
  labels: {{- include "twistlock-console.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
stringData:
  TWISTLOCK_METRICS_USER: "bigbang-metrics-sa"
  TWISTLOCK_METRICS_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
