apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "twistlock-console.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "twistlock-console.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.console.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.console.persistence.size }}