{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "twistlock-console.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "twistlock-console.labels" . | nindent 4 }}
    release: monitoring
spec:
  selector:
    matchLabels: {{- include "twistlock-console.selector" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - interval: 30s
      path: /api/v1/metrics
      port: mgmt-http
      scheme: http
      basicAuth:
        password:
          name: twistlock-basic-auth
          key: password
        username:
          name: twistlock-basic-auth
          key: user
  jobLabel: twistlock-metrics
{{- end }}