apiVersion: v1
kind: Service
metadata:
  name: {{ template "twistlock-console.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "twistlock-console.labels" . | nindent 4 }}
spec:
  ports:
  - name: tcp-communication-port
    port: {{ .Values.console.ports.communication }}
  - name: http-management-port-https
    port: {{ .Values.console.ports.managementHttps }}
  - name: http-mgmt-http
    port: {{ .Values.console.ports.managementHttp }}
  selector: {{- include "twistlock-console.selector" . | nindent 4 }}