---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: console
  name: twistlock-console
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: tcp-communication-port
    port: 8084
  - name: http-management-port-https
    port: 8083
  - name: http-mgmt-http
    port: 8081
  selector:
    name: twistlock-console
