apiVersion: v1
kind: Service
metadata:
  name: {{ template "twistlock-console.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "twistlock-console.labels" . | nindent 4 }}
spec:
  ports:
  - name: tcp-communication-port
    port: 8084
  - name: http-management-port-https
    port: 8083
  - name: http-mgmt-http
    port: 8081
  selector: {{- include "twistlock-console.selector" . | nindent 4 }}