{{- if and .Values.istio.enabled (eq .Values.istio.mtls.mode "STRICT") }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: twistlock-console-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      name: twistlock-console
  portLevelMtls:
    "8084":
      mode: PERMISSIVE
{{- end }}