{{- /* Render Istio ServiceEntries */ -}}
{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ .Release.Name }}-intellegence-sidecar
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
    - intelligence.twistlock.com 
  location: MESH_EXTERNAL
  exportTo: 
  - "."
  ports:
    - number: 443
      protocol: TLS
      name: https
---
{{- end -}}
