{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-defender-to-console
  namespace: {{ .Release.Namespace }}
  labels: {{- include "twistlock-console.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "twistlock-console.selector" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
  {{- if .Values.networkPolicies.nodeCidr }}
      - ipBlock:
          cidr: {{ .Values.networkPolicies.nodeCidr }}
  {{- else }}
      {{- range tuple "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" }}
      - ipBlock:
          cidr: {{ . }}
      {{- end }}
  {{- end }}
      ports:
      - port: {{ .Values.console.ports.communication }}
{{- end }}
