{{- if .Values.networkPolicies.enabled}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: "{{ .Release.Namespace }}"
  labels: {{- include "twistlock-console.labels" . | nindent 4 }}
spec:
  podSelector: {}
  ingress: []
  policyTypes:
    - Ingress
{{- end }}