{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-allow-ns
  namespace: "{{ .Release.Namespace }}"
spec:
  ingress:
    - from:
      - podSelector: {} # all pods in namespace
  podSelector: {} # all pods
  policyTypes:
    - Ingress
{{- end }}
