{{- if and .Values.networkPolicies.enabled .Values.monitoring.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-scraping
  namespace: "{{ .Release.Namespace }}"
  labels: {{- include "twistlock-console.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            app.kubernetes.io/name: monitoring
        podSelector:
          matchLabels:
            app: prometheus
      ports:
      - port: 8081
  podSelector:
    matchLabels: {{- include "twistlock-console.selector" . | nindent 6 }}
  policyTypes:
    - Ingress
{{- end }}
