{{- if and .Values.istio.enabled (eq .Values.istio.mtls.mode "STRICT") }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: twistlock-console-exception
  namespace: {{ .Release.Namespace }}
  labels: {{- include "twistlock-console.labels" . | nindent 4 }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      {{- include "twistlock-console.selector" . | nindent 8 }}
  portLevelMtls:
    "{{ .Values.console.ports.communication }}":
      mode: PERMISSIVE
{{- end }}