{{- if and .Values.istio.enabled (eq .Values.istio.mtls.mode "STRICT") }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: twistlock-defender-exception
  namespace: {{ .Release.Namespace }}
  labels: {{- include "twistlock-console.labels" . | nindent 4 }}
spec:
  mtls:
    mode: PERMISSIVE
  selector:
    matchLabels: {{- include "twistlock-defender.selector" . | nindent 6 }}
{{- end }}
