{
 "title": "Compute Prometheus Counters",
 "tags": [ "twistlock" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "API Requests to Console",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(twistlock_api_requests{job=\"twistlock-console\"}[1m]))",
     "legendFormat": "api_requests"
    }
   ]
  },
  {
   "title": "Total API Requests to Console",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "twistlock_api_requests{job=\"twistlock-console\"}",
     "legendFormat": "api_requests"
    }
   ]
  },
  {
   "title": "Defender Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(twistlock_defender_events{job=\"twistlock-console\"}[1m]))",
     "legendFormat": "defender_events"
    }
   ]
  },
  {
   "title": "Defender Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "twistlock_defender_events{job=\"twistlock-console\"}",
     "legendFormat": "defender_events"
    }
   ]
  }
 ]
}