{{- if and .Values.init.enabled .Values.defender.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "twistlock-init.name" . }}
  labels: {{- include "twistlock-init.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "apps"
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - services
  - secrets
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - endpoints
  - namespaces
  - pods
  - pods/proxy
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "networking.istio.io"
  resources:
  - destinationrules
  - gateways
  - virtualservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "security.istio.io"
  resources:
  - authorizationpolicies
  - peerauthentications
  verbs:
  - get
  - list
  - watch
{{- end }}