{{- if and .Values.init.enabled .Values.policies.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "twistlock-defender.name" . }}-policies
  labels: {{- include "twistlock-init.labels" . | nindent 4 }}
stringData:
  TWISTLOCK_POLICY_COMPLIANCE_ALERT_THRESHOLD: {{ .Values.policies.compliance.alertThreshold }}
  TWISTLOCK_POLICY_COMPLIANCE_ENABLED: {{ .Values.policies.compliance.enabled | quote }}
  {{- if .Values.policies.compliance.templates }}
  TWISTLOCK_POLICY_COMPLIANCE_TEMPLATES: |-
    {{- range .Values.policies.compliance.templates }}
    {{ . }}
    {{- end }}
  {{- end }}
  TWISTLOCK_POLICY_ENABLED: "true"
  TWISTLOCK_POLICY_NAME: {{ .Values.policies.name }}
  TWISTLOCK_POLICY_RUNTIME_ENABLED: {{ .Values.policies.runtime.enabled | quote }}
  TWISTLOCK_POLICY_VULNERABILITIES_ALERT_THRESHOLD: {{ .Values.policies.vulnerabilities.alertThreshold }}
  TWISTLOCK_POLICY_VULNERABILITIES_ENABLED: {{ .Values.policies.vulnerabilities.enabled | quote }}
  TWISTLOCK_RUNTIME_CONTAINER_POLICY_RULE_JSON: |-
    {{- .Files.Get "policies/runtime/container-policy/runtime-container-policy-rule.json" | nindent 4 }}
  TWISTLOCK_RUNTIME_HOST_POLICY_RULE_JSON: |-
    {{- .Files.Get "policies/runtime/host-policy/runtime-host-policy-rule.json" | nindent 4 }}
  TWISTLOCK_RUNTIME_SERVERLESS_POLICY_RULE_JSON: |-
    {{- .Files.Get "policies/runtime/serverless-policy/runtime-serverless-policy-rule.json" | nindent 4 }}
{{- end }}