{{- if and .Values.init.enabled .Values.defender.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "twistlock-defender.name" . }}
  labels: {{- include "twistlock-init.labels" . | nindent 4 }}
stringData:
  # Required items: orchestration, console/port, proxy, namespace, monitor service accounts, monitor istio, image, and privileged
  {{- if .Values.defender.clusterName }}
  TWISTLOCK_CLUSTER: {{ .Values.defender.clusterName }}
  {{- end }}
  {{- if .Values.defender.collectLabels }}
  TWISTLOCK_COLLECT_LABELS: "true"
  {{- end }}
  {{- if .Values.defender.cri }}
  TWISTLOCK_CRI: "true"
  {{- end }}
  TWISTLOCK_DEFENDER_ENABLED: "true"
  {{- if (and .Values.defender.image.repository .Values.defender.image.tag) }}
  TWISTLOCK_DEFENDER_IMAGE: {{ .Values.defender.image.repository }}:{{ .Values.defender.image.tag }}
  {{- end }}
  {{- if .Values.defender.dockerSocket }}
  TWISTLOCK_DOCKER_SOCKET: {{ .Values.defender.dockerSocket }}
  {{- end }}
  {{- if .Values.istio.enabled }}
  TWISTLOCK_MONITOR_ISTIO: "true"
  {{- end }}
  {{- if .Values.defender.monitorServiceAccounts }}
  TWISTLOCK_MONITOR_SERVICE_ACCOUNTS: "true"
  {{- end }}
  TWISTLOCK_NAMESPACE: {{ .Release.Namespace }}
  {{- if .Values.nodeSelector }}
  TWISTLOCK_NODE_SELECTOR: {{ .Values.nodeSelector }}
  {{- end }}
  {{- if .Values.defender.tolerations }}
  TWISTLOCK_DEFENDER_TOLERATIONS: {{ .Values.defender.tolerations | toYaml | indent 4 | quote }}
  {{- end }}
  {{- if .Values.defender.securityCapabilitiesDrop }}
  TWISTLOCK_DEFENDER_SECURITYCONTEXT_DROP_CAPABILITIES: {{ .Values.defender.securityCapabilitiesDrop | toYaml | indent 4 | quote }}
  {{- end }}
  TWISTLOCK_ORCHESTRATION: {{ if .Values.openshift }}openshift{{ else }}kubernetes{{ end }}
  {{- if (or .Values.defender.selinux .Values.defender.privileged) }}
  TWISTLOCK_PRIVILEGED: {{ if .Values.defender.selinux }}"false"{{ else }}{{ .Values.defender.privileged | quote }}{{ end }}
  {{- end }}
  {{- if (dig "proxy" "address" nil .Values.defender) }}
  TWISTLOCK_PROXY_ADDR: {{ .Values.defender.proxy.address }}
  {{- end }}
  {{- if (dig "proxy" "ca" nil .Values.defender) }}
  TWISTLOCK_PROXY_CA: {{ .Values.defender.proxy.ca }}
  {{- end }}
  {{- if (dig "proxy" "password" nil .Values.defender) }}
  TWISTLOCK_PROXY_PASSWORD: {{ .Values.defender.proxy.password }}
  {{- end }}
  {{- if (dig "proxy" "username" nil .Values.defender) }}
  TWISTLOCK_PROXY_USERNAME: {{ .Values.defender.proxy.username }}
  {{- end }}
  {{- if .Values.imagePullSecrets }}
  TWISTLOCK_PULL_SECRET: {{ (.Values.imagePullSecrets | first).name }}
  {{- end }}
  {{- if .Values.defender.selinux }}
  TWISTLOCK_SELINUX: "true"
  {{- end }}
  {{- if .Values.defender.uniqueHostName }}
  TWISTLOCK_UNIQUE_HOSTS: "true"
  {{- end }}
{{- end }}
