{{- if and .Values.init.enabled .Values.sso.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "twistlock-sso.name" . }}
  labels: {{- include "twistlock-init.labels" . | nindent 4 }}
stringData:
  TWISTLOCK_SSO_ENABLED: "true"
  {{- if .Values.sso.client_id }}
  TWISTLOCK_SSO_CLIENT_ID: {{ .Values.sso.client_id }}
  {{- end }}
  {{- if .Values.sso.provider_name }}
  TWISTLOCK_SSO_PROVIDER_NAME: {{ .Values.sso.provider_name }}
  {{- end }}
  {{- if .Values.sso.provider_type }}
  TWISTLOCK_SSO_PROVIDER_TYPE: {{ .Values.sso.provider_type }}
  {{- end }}
  {{- if .Values.sso.issuer_uri }}
  TWISTLOCK_SSO_ISSUER_URI: {{ .Values.sso.issuer_uri }}
  {{- end }}
  {{- if .Values.sso.idp_url }}
  TWISTLOCK_SSO_IDP_URL: {{ .Values.sso.idp_url }}
  {{- end }}
  {{- if .Values.sso.console_url }}
  TWISTLOCK_SSO_CONSOLE_URL: {{ .Values.sso.console_url }}
  {{- end }}
  {{- if .Values.sso.groups }}
  TWISTLOCK_SSO_GROUPS: {{ .Values.sso.groups }}
  {{- end }}
  {{- if .Values.sso.cert }}
  TWISTLOCK_SSO_CERT: {{ .Values.sso.cert | quote }}
  {{- end }}
{{- end }}