{{- if and .Values.console.volumeUpgrade .Release.IsUpgrade }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volume-upgrade-svc-acct
  labels: {{- include "twistlock-init.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
{{- end }}
