{{- if and .Values.console.volumeUpgrade .Release.IsUpgrade }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: volume-upgrade-rolebinding
  labels: {{- include "twistlock-init.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-30"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: volume-upgrade-role
subjects:
  - kind: ServiceAccount
    name: volume-upgrade-svc-acct
    namespace: {{ .Release.Namespace }}
{{- end }}
