{{- if and .Values.console.volumeUpgrade .Release.IsUpgrade }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: volume-upgrade-role
  labels: {{- include "twistlock-init.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["patch", "get", "list", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]  
{{- end }}
